language: cpp

sudo: required

compiler:
- clang

os: linux
addons:
    apt:
        sources:
            - llvm-toolchain-precise-5.0
            - ubuntu-toolchain-r-test
        packages:
            - clang-5.0
            - ocl-icd-opencl-dev
            - libgdal-dev

install: ./travis.sh

script: 
- cd build && make