language: cpp

sudo: required

compiler:
- clang

os: linux
env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.8
            - ocl-icd-opencl-dev
            - libgdal-dev

install: ./travis.sh

script: 
- cd build && make