language: cpp

sudo: required

compiler:
- clang

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.6
            - ocl-icd-opencl-dev
            - libgdal-dev

install: ./travis.sh

script: 
- cd build && make